/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopony;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Font;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author visio
 */
public class Main extends javax.swing.JFrame {

    private Map map;
    private Player player;
    private ArrayList<JPanel> boardBlocks;
    private ImageIcon default_img = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d0.png");
    private ImageIcon img1 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d1.png");
    private ImageIcon img2 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d2.png");
    private ImageIcon img3 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d3.png");
    private ImageIcon img4 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d4.png");
    private ImageIcon img5 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d5.png");
    private ImageIcon img6 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\d6.png");
    private ImageIcon[] imgSet = {img1, img2, img3, img4, img5, img6};

    /**
     * Creates new form Main
     */
    public Main(Player p) {
       this.player = p;
        this.setAlwaysOnTop(true);
        map = new Map();
        initComponents();
        MoneyPanel.setText("$" + p.getMoney());
        ((JLayeredPane) BoardPanel.getComponent(0)).add(p.getPanel(), JLayeredPane.DRAG_LAYER);//*
        ((JLayeredPane) BoardPanel.getComponent(0)).revalidate();//*
        ((JLayeredPane) BoardPanel.getComponent(0)).repaint();//*
        //for(int i = 0; i<39;i++){
        //BoardPanel.getComponent(0).setBackground(Color.red);
        //}
        //jLayeredPane1.add(player.getPanel(),JLayeredPane.DRAG_LAYER);
        //jPanel24.validate();
        //jPanel24.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noMoneyDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        popup = new javax.swing.JDialog();
        pic = new javax.swing.JLabel();
        DeedPanel = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        SubDeed = new javax.swing.JPanel();
        BoardPanel = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        Go_Start = map.getMap().get(0).getMap_panel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        JacobField = map.getMap().get(1).getMap_panel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        Chest1 = map.getMap().get(2).getMap_panel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        TexasStadium = map.getMap().get(3).getMap_panel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        Tax = map.getMap().get(4).getMap_panel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        ORD = map.getMap().get(5).getMap_panel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        Grand_Ole_Opry = map.getMap().get(6).getMap_panel();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        Chance1 = map.getMap().get(7).getMap_panel();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        Gateway_of_Arch = map.getMap().get(8).getMap_panel();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        Mall_of_America = map.getMap().get(9).getMap_panel();
        jLayeredPane12 = new javax.swing.JLayeredPane();
        VisitingJail = map.getMap().get(10).getMap_panel();
        jLayeredPane13 = new javax.swing.JLayeredPane();
        Olympic_Park = map.getMap().get(11).getMap_panel();
        jLayeredPane14 = new javax.swing.JLayeredPane();
        Mobile_Service = map.getMap().get(12).getMap_panel();
        jLayeredPane15 = new javax.swing.JLayeredPane();
        Red_Rocks = map.getMap().get(13).getMap_panel();
        jLayeredPane16 = new javax.swing.JLayeredPane();
        Liberty_Bell = map.getMap().get(14).getMap_panel();
        jLayeredPane17 = new javax.swing.JLayeredPane();
        LAX = map.getMap().get(15).getMap_panel();
        jLayeredPane18 = new javax.swing.JLayeredPane();
        South_Beach = map.getMap().get(16).getMap_panel();
        jLayeredPane19 = new javax.swing.JLayeredPane();
        Chest2 = map.getMap().get(17).getMap_panel();
        jLayeredPane20 = new javax.swing.JLayeredPane();
        Johnson = map.getMap().get(18).getMap_panel();
        jLayeredPane21 = new javax.swing.JLayeredPane();
        Pioneer_Square = map.getMap().get(19).getMap_panel();
        jLayeredPane22 = new javax.swing.JLayeredPane();
        Free_Parking = map.getMap().get(20).getMap_panel();
        jLayeredPane23 = new javax.swing.JLayeredPane();
        CamelBack = map.getMap().get(21).getMap_panel();
        jLayeredPane24 = new javax.swing.JLayeredPane();
        Chance2 = map.getMap().get(22).getMap_panel();
        jLayeredPane25 = new javax.swing.JLayeredPane();
        Waikiki = map.getMap().get(23).getMap_panel();
        jLayeredPane26 = new javax.swing.JLayeredPane();
        DisneyWorld = map.getMap().get(24).getMap_panel();
        jLayeredPane27 = new javax.swing.JLayeredPane();
        JFK = map.getMap().get(25).getMap_panel();
        jLayeredPane28 = new javax.swing.JLayeredPane();
        French_Quarter = map.getMap().get(26).getMap_panel();
        jLayeredPane29 = new javax.swing.JLayeredPane();
        Hollywood = map.getMap().get(27).getMap_panel();
        jLayeredPane30 = new javax.swing.JLayeredPane();
        Internet_Service = map.getMap().get(28).getMap_panel();
        jLayeredPane31 = new javax.swing.JLayeredPane();
        GoldenGate = map.getMap().get(29).getMap_panel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        GoToJail = map.getMap().get(30).getMap_panel();
        jLayeredPane32 = new javax.swing.JLayeredPane();
        LasVegas = map.getMap().get(31).getMap_panel();
        jLayeredPane33 = new javax.swing.JLayeredPane();
        Wrigley_Field = map.getMap().get(32).getMap_panel();
        jLayeredPane34 = new javax.swing.JLayeredPane();
        Chest3 = map.getMap().get(33).getMap_panel();
        jLayeredPane35 = new javax.swing.JLayeredPane();
        White_House = map.getMap().get(34).getMap_panel();
        jLayeredPane36 = new javax.swing.JLayeredPane();
        ATL = map.getMap().get(35).getMap_panel();
        jLayeredPane37 = new javax.swing.JLayeredPane();
        Chance3 = map.getMap().get(36).getMap_panel();
        jLayeredPane38 = new javax.swing.JLayeredPane();
        Fenway_Park = map.getMap().get(37).getMap_panel();
        jLayeredPane39 = new javax.swing.JLayeredPane();
        Credit_Card = map.getMap().get(38).getMap_panel();
        jLayeredPane40 = new javax.swing.JLayeredPane();
        Time_Square = map.getMap().get(39).getMap_panel();
        jPanel41 = new javax.swing.JPanel();
        InfoPanel = new javax.swing.JPanel();
        MoneyPanel = new javax.swing.JTextField();
        buyButt = new javax.swing.JButton();
        sellButt = new javax.swing.JButton();
        owner = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();

        noMoneyDialog.setLocation(new java.awt.Point(1000, 500));
        noMoneyDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        noMoneyDialog.setResizable(false);
        noMoneyDialog.setSize(new java.awt.Dimension(286, 120));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/card/moneynotenough.png"))); // NOI18N

        javax.swing.GroupLayout noMoneyDialogLayout = new javax.swing.GroupLayout(noMoneyDialog.getContentPane());
        noMoneyDialog.getContentPane().setLayout(noMoneyDialogLayout);
        noMoneyDialogLayout.setHorizontalGroup(
            noMoneyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        noMoneyDialogLayout.setVerticalGroup(
            noMoneyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, Short.MAX_VALUE)
        );

        popup.setAlwaysOnTop(true);
        popup.setLocation(new java.awt.Point(650, 350));
        popup.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        popup.setSize(new java.awt.Dimension(295, 360));
        popup.getContentPane().add(pic, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        DeedPanel.setBackground(new java.awt.Color(51, 51, 51));
        DeedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 10));
        DeedPanel.setPreferredSize(new java.awt.Dimension(350, 900));

        scrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        scrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane1.setMinimumSize(new java.awt.Dimension(350, 900));

        SubDeed.setBackground(new java.awt.Color(54, 185, 148));
        SubDeed.setLayout(new java.awt.GridLayout(20, 1));
        scrollPane1.add(SubDeed);

        javax.swing.GroupLayout DeedPanelLayout = new javax.swing.GroupLayout(DeedPanel);
        DeedPanel.setLayout(DeedPanelLayout);
        DeedPanelLayout.setHorizontalGroup(
            DeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeedPanelLayout.setVerticalGroup(
            DeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(DeedPanel);

        BoardPanel.setBackground(new java.awt.Color(51, 51, 51));
        BoardPanel.setMinimumSize(new java.awt.Dimension(880, 900));
        BoardPanel.setPreferredSize(new java.awt.Dimension(880, 900));
        BoardPanel.setLayout(null);

        Go_Start.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Go_Start.setPreferredSize(new java.awt.Dimension(100, 100));
        Go_Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Go_StartMouseClicked(evt);
            }
        });
        Go_Start.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane4.add(Go_Start);
        Go_Start.setBounds(0, 0, 110, 120);
        Go_Start.getAccessibleContext().setAccessibleName("1");

        BoardPanel.add(jLayeredPane4);
        jLayeredPane4.setBounds(760, 740, 110, 120);

        jLayeredPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseClicked(evt);
            }
        });

        JacobField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        JacobField.setPreferredSize(new java.awt.Dimension(70, 100));
        JacobField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JacobFieldMouseClicked(evt);
            }
        });
        JacobField.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane5.add(JacobField);
        JacobField.setBounds(0, 0, 80, 120);

        BoardPanel.add(jLayeredPane5);
        jLayeredPane5.setBounds(680, 740, 80, 120);

        Chest1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chest1.setPreferredSize(new java.awt.Dimension(70, 100));
        Chest1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chest1MouseClicked(evt);
            }
        });
        Chest1.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane6.add(Chest1);
        Chest1.setBounds(0, 0, 60, 120);

        BoardPanel.add(jLayeredPane6);
        jLayeredPane6.setBounds(620, 740, 60, 120);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 5));

        TexasStadium.setPreferredSize(new java.awt.Dimension(70, 100));
        TexasStadium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TexasStadiumMouseClicked(evt);
            }
        });
        TexasStadium.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane1.add(TexasStadium);
        TexasStadium.setBounds(5, 5, 60, 110);

        BoardPanel.add(jLayeredPane1);
        jLayeredPane1.setBounds(550, 740, 70, 120);

        jLayeredPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane7MouseClicked(evt);
            }
        });

        Tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Tax.setPreferredSize(new java.awt.Dimension(70, 100));
        Tax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaxMouseClicked(evt);
            }
        });
        Tax.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane7.add(Tax);
        Tax.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane7);
        jLayeredPane7.setBounds(480, 740, 70, 120);

        ORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        ORD.setPreferredSize(new java.awt.Dimension(70, 100));
        ORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ORDMouseClicked(evt);
            }
        });
        ORD.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane3.add(ORD);
        ORD.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane3);
        jLayeredPane3.setBounds(410, 740, 70, 120);

        Grand_Ole_Opry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Grand_Ole_Opry.setPreferredSize(new java.awt.Dimension(70, 100));
        Grand_Ole_Opry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grand_Ole_OpryMouseClicked(evt);
            }
        });
        Grand_Ole_Opry.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane8.add(Grand_Ole_Opry);
        Grand_Ole_Opry.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane8);
        jLayeredPane8.setBounds(340, 740, 70, 120);

        Chance1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chance1.setPreferredSize(new java.awt.Dimension(70, 100));
        Chance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chance1MouseClicked(evt);
            }
        });
        Chance1.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane9.add(Chance1);
        Chance1.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane9);
        jLayeredPane9.setBounds(270, 740, 70, 120);

        Gateway_of_Arch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Gateway_of_Arch.setPreferredSize(new java.awt.Dimension(70, 100));
        Gateway_of_Arch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Gateway_of_ArchMouseClicked(evt);
            }
        });
        Gateway_of_Arch.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane10.add(Gateway_of_Arch);
        Gateway_of_Arch.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane10);
        jLayeredPane10.setBounds(200, 740, 70, 120);

        Mall_of_America.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Mall_of_America.setPreferredSize(new java.awt.Dimension(70, 100));
        Mall_of_America.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mall_of_AmericaMouseClicked(evt);
            }
        });
        Mall_of_America.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane11.add(Mall_of_America);
        Mall_of_America.setBounds(0, 0, 70, 120);

        BoardPanel.add(jLayeredPane11);
        jLayeredPane11.setBounds(130, 740, 70, 120);

        VisitingJail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        VisitingJail.setPreferredSize(new java.awt.Dimension(100, 100));
        VisitingJail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitingJailMouseClicked(evt);
            }
        });
        VisitingJail.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane12.add(VisitingJail);
        VisitingJail.setBounds(0, 0, 120, 120);
        VisitingJail.getAccessibleContext().setAccessibleName("10");

        BoardPanel.add(jLayeredPane12);
        jLayeredPane12.setBounds(10, 740, 120, 120);

        Olympic_Park.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Olympic_Park.setForeground(new java.awt.Color(0, 204, 204));
        Olympic_Park.setPreferredSize(new java.awt.Dimension(100, 70));
        Olympic_Park.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Olympic_ParkMouseClicked(evt);
            }
        });
        Olympic_Park.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane13.add(Olympic_Park);
        Olympic_Park.setBounds(0, 0, 120, 60);

        BoardPanel.add(jLayeredPane13);
        jLayeredPane13.setBounds(10, 680, 120, 60);

        Mobile_Service.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Mobile_Service.setForeground(new java.awt.Color(0, 204, 204));
        Mobile_Service.setPreferredSize(new java.awt.Dimension(100, 70));
        Mobile_Service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mobile_ServiceMouseClicked(evt);
            }
        });
        Mobile_Service.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane14.add(Mobile_Service);
        Mobile_Service.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane14);
        jLayeredPane14.setBounds(10, 610, 120, 70);

        Red_Rocks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Red_Rocks.setForeground(new java.awt.Color(0, 204, 204));
        Red_Rocks.setPreferredSize(new java.awt.Dimension(100, 70));
        Red_Rocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Red_RocksMouseClicked(evt);
            }
        });
        Red_Rocks.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane15.add(Red_Rocks);
        Red_Rocks.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane15);
        jLayeredPane15.setBounds(10, 540, 120, 70);

        Liberty_Bell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Liberty_Bell.setForeground(new java.awt.Color(0, 204, 204));
        Liberty_Bell.setPreferredSize(new java.awt.Dimension(100, 70));
        Liberty_Bell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Liberty_BellMouseClicked(evt);
            }
        });
        Liberty_Bell.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane16.add(Liberty_Bell);
        Liberty_Bell.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane16);
        jLayeredPane16.setBounds(10, 470, 120, 70);

        LAX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        LAX.setForeground(new java.awt.Color(0, 204, 204));
        LAX.setPreferredSize(new java.awt.Dimension(100, 70));
        LAX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAXMouseClicked(evt);
            }
        });
        LAX.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane17.add(LAX);
        LAX.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane17);
        jLayeredPane17.setBounds(10, 400, 120, 70);

        South_Beach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        South_Beach.setForeground(new java.awt.Color(0, 204, 204));
        South_Beach.setPreferredSize(new java.awt.Dimension(100, 70));
        South_Beach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                South_BeachMouseClicked(evt);
            }
        });
        South_Beach.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane18.add(South_Beach);
        South_Beach.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane18);
        jLayeredPane18.setBounds(10, 330, 120, 70);

        Chest2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chest2.setForeground(new java.awt.Color(0, 204, 204));
        Chest2.setPreferredSize(new java.awt.Dimension(100, 70));
        Chest2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chest2MouseClicked(evt);
            }
        });
        Chest2.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane19.add(Chest2);
        Chest2.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane19);
        jLayeredPane19.setBounds(10, 260, 120, 70);

        Johnson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Johnson.setForeground(new java.awt.Color(0, 204, 204));
        Johnson.setPreferredSize(new java.awt.Dimension(100, 70));
        Johnson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JohnsonMouseClicked(evt);
            }
        });
        Johnson.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane20.add(Johnson);
        Johnson.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane20);
        jLayeredPane20.setBounds(10, 190, 120, 70);

        Pioneer_Square.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Pioneer_Square.setForeground(new java.awt.Color(0, 204, 204));
        Pioneer_Square.setPreferredSize(new java.awt.Dimension(100, 70));
        Pioneer_Square.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pioneer_SquareMouseClicked(evt);
            }
        });
        Pioneer_Square.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane21.add(Pioneer_Square);
        Pioneer_Square.setBounds(0, 0, 120, 70);

        BoardPanel.add(jLayeredPane21);
        jLayeredPane21.setBounds(10, 120, 120, 70);

        Free_Parking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Free_Parking.setForeground(new java.awt.Color(0, 204, 204));
        Free_Parking.setPreferredSize(new java.awt.Dimension(100, 100));
        Free_Parking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Free_ParkingMouseClicked(evt);
            }
        });
        Free_Parking.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane22.add(Free_Parking);
        Free_Parking.setBounds(0, 0, 120, 110);
        Free_Parking.getAccessibleContext().setAccessibleName("30");
        Free_Parking.getAccessibleContext().setAccessibleDescription("Ded");

        BoardPanel.add(jLayeredPane22);
        jLayeredPane22.setBounds(10, 10, 120, 110);

        CamelBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        CamelBack.setForeground(new java.awt.Color(0, 204, 204));
        CamelBack.setMinimumSize(new java.awt.Dimension(70, 100));
        CamelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamelBackMouseClicked(evt);
            }
        });
        CamelBack.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane23.add(CamelBack);
        CamelBack.setBounds(0, 0, 70, 110);
        CamelBack.getAccessibleContext().setAccessibleName("");

        BoardPanel.add(jLayeredPane23);
        jLayeredPane23.setBounds(130, 10, 70, 110);

        Chance2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chance2.setForeground(new java.awt.Color(0, 204, 204));
        Chance2.setMinimumSize(new java.awt.Dimension(70, 100));
        Chance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chance2MouseClicked(evt);
            }
        });
        Chance2.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane24.add(Chance2);
        Chance2.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane24);
        jLayeredPane24.setBounds(200, 10, 70, 110);

        Waikiki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Waikiki.setForeground(new java.awt.Color(0, 204, 204));
        Waikiki.setMinimumSize(new java.awt.Dimension(70, 100));
        Waikiki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaikikiMouseClicked(evt);
            }
        });
        Waikiki.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane25.add(Waikiki);
        Waikiki.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane25);
        jLayeredPane25.setBounds(270, 10, 70, 110);

        DisneyWorld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        DisneyWorld.setMinimumSize(new java.awt.Dimension(70, 100));
        DisneyWorld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisneyWorldMouseClicked(evt);
            }
        });
        DisneyWorld.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane26.add(DisneyWorld);
        DisneyWorld.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane26);
        jLayeredPane26.setBounds(340, 10, 70, 110);

        JFK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        JFK.setMinimumSize(new java.awt.Dimension(70, 100));
        JFK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JFKMouseClicked(evt);
            }
        });
        JFK.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane27.add(JFK);
        JFK.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane27);
        jLayeredPane27.setBounds(410, 10, 70, 110);

        French_Quarter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        French_Quarter.setMinimumSize(new java.awt.Dimension(70, 100));
        French_Quarter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                French_QuarterMouseClicked(evt);
            }
        });
        French_Quarter.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane28.add(French_Quarter);
        French_Quarter.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane28);
        jLayeredPane28.setBounds(480, 10, 70, 110);

        Hollywood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Hollywood.setMinimumSize(new java.awt.Dimension(70, 100));
        Hollywood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HollywoodMouseClicked(evt);
            }
        });
        Hollywood.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane29.add(Hollywood);
        Hollywood.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane29);
        jLayeredPane29.setBounds(550, 10, 70, 110);

        Internet_Service.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Internet_Service.setMinimumSize(new java.awt.Dimension(70, 100));
        Internet_Service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Internet_ServiceMouseClicked(evt);
            }
        });
        Internet_Service.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane30.add(Internet_Service);
        Internet_Service.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane30);
        jLayeredPane30.setBounds(620, 10, 70, 110);

        GoldenGate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        GoldenGate.setMinimumSize(new java.awt.Dimension(70, 100));
        GoldenGate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoldenGateMouseClicked(evt);
            }
        });
        GoldenGate.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane31.add(GoldenGate);
        GoldenGate.setBounds(0, 0, 70, 110);

        BoardPanel.add(jLayeredPane31);
        jLayeredPane31.setBounds(690, 10, 70, 110);

        GoToJail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        GoToJail.setPreferredSize(new java.awt.Dimension(100, 100));
        GoToJail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoToJailMouseClicked(evt);
            }
        });
        GoToJail.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane2.add(GoToJail);
        GoToJail.setBounds(0, 0, 110, 110);
        GoToJail.getAccessibleContext().setAccessibleName("");

        BoardPanel.add(jLayeredPane2);
        jLayeredPane2.setBounds(760, 10, 110, 110);

        LasVegas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        LasVegas.setPreferredSize(new java.awt.Dimension(100, 70));
        LasVegas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LasVegasMouseClicked(evt);
            }
        });
        LasVegas.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane32.add(LasVegas);
        LasVegas.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane32);
        jLayeredPane32.setBounds(760, 120, 110, 70);

        Wrigley_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Wrigley_Field.setPreferredSize(new java.awt.Dimension(100, 70));
        Wrigley_Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Wrigley_FieldMouseClicked(evt);
            }
        });
        Wrigley_Field.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane33.add(Wrigley_Field);
        Wrigley_Field.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane33);
        jLayeredPane33.setBounds(760, 190, 110, 70);

        Chest3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chest3.setPreferredSize(new java.awt.Dimension(100, 70));
        Chest3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chest3MouseClicked(evt);
            }
        });
        Chest3.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane34.add(Chest3);
        Chest3.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane34);
        jLayeredPane34.setBounds(760, 260, 110, 70);

        White_House.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        White_House.setPreferredSize(new java.awt.Dimension(100, 70));
        White_House.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                White_HouseMouseClicked(evt);
            }
        });
        White_House.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane35.add(White_House);
        White_House.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane35);
        jLayeredPane35.setBounds(760, 330, 110, 70);

        ATL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        ATL.setPreferredSize(new java.awt.Dimension(100, 70));
        ATL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATLMouseClicked(evt);
            }
        });
        ATL.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane36.add(ATL);
        ATL.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane36);
        jLayeredPane36.setBounds(760, 400, 110, 70);

        Chance3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Chance3.setPreferredSize(new java.awt.Dimension(100, 70));
        Chance3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chance3MouseClicked(evt);
            }
        });
        Chance3.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane37.add(Chance3);
        Chance3.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane37);
        jLayeredPane37.setBounds(760, 470, 110, 70);

        Fenway_Park.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Fenway_Park.setPreferredSize(new java.awt.Dimension(100, 70));
        Fenway_Park.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fenway_ParkMouseClicked(evt);
            }
        });
        Fenway_Park.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane38.add(Fenway_Park);
        Fenway_Park.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane38);
        jLayeredPane38.setBounds(760, 540, 110, 70);

        Credit_Card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Credit_Card.setPreferredSize(new java.awt.Dimension(100, 70));
        Credit_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Credit_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Credit_CardMouseEntered(evt);
            }
        });
        Credit_Card.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane39.add(Credit_Card);
        Credit_Card.setBounds(0, 0, 110, 70);

        BoardPanel.add(jLayeredPane39);
        jLayeredPane39.setBounds(760, 610, 110, 70);

        Time_Square.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        Time_Square.setPreferredSize(new java.awt.Dimension(100, 70));
        Time_Square.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Time_SquareMouseClicked(evt);
            }
        });
        Time_Square.setLayout(new java.awt.GridLayout(1, 1));
        jLayeredPane40.add(Time_Square);
        Time_Square.setBounds(0, 0, 110, 60);

        BoardPanel.add(jLayeredPane40);
        jLayeredPane40.setBounds(760, 680, 110, 60);

        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 5));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        BoardPanel.add(jPanel41);
        jPanel41.setBounds(130, 120, 630, 620);

        getContentPane().add(BoardPanel);

        InfoPanel.setBackground(new java.awt.Color(51, 51, 51));

        MoneyPanel.setEditable(false);
        MoneyPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyPanelActionPerformed(evt);
            }
        });

        buyButt.setText("BUY");
        buyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtActionPerformed(evt);
            }
        });

        sellButt.setText("SELL");
        sellButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtActionPerformed(evt);
            }
        });

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        jButton3.setText("Roll");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dice1.setIcon(default_img);

        dice2.setIcon(default_img);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoneyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(InfoPanelLayout.createSequentialGroup()
                                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(InfoPanelLayout.createSequentialGroup()
                                    .addComponent(buyButt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sellButt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MoneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyButt, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(sellButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        getContentPane().add(InfoPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoneyPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyPanelActionPerformed

    private void buyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtActionPerformed
        // TODO add your handling code here:
        System.out.println(player.getIndex());
        if (player.getMoney() < map.getMap().get(player.getIndex()).getPrice()) {
            noMoneyDialog.setAlwaysOnTop(true);
            noMoneyDialog.setVisible(true);
            return;
        }
        if (map.getMap().get(player.getIndex()).getClass() == Deed.class) {
            if (map.getMap().get(player.getIndex()).getOwner_name() == "None") {
                buyButt.setText("Buy");
                SubDeed.add(map.getMap().get(player.getIndex()).getDeed_panel());
                ((Deed) map.getMap().get(player.getIndex())).setOwner(player);
                ((Deed) map.getMap().get(player.getIndex())).setOwner_name(player.getName());
                ((Deed) map.getMap().get(player.getIndex())).setBought(true);
                player.addMoney(((Deed) map.getMap().get(player.getIndex())).getPrice() * -1);
                player.getDeeds().add((Deed) map.getMap().get(player.getIndex()));
            }
            if (map.getMap().get(player.getIndex()).getOwner_name().equals(player.getName())) {
                if (((Deed) map.getMap().get(player.getIndex())).getHouse() >= 0 && ((Deed) map.getMap().get(player.getIndex())).getHouse() < 4 && ((Deed) map.getMap().get(player.getIndex())).isBought()) {
                    buyButt.setText("Buy House");
                    ((Deed) map.getMap().get(player.getIndex())).add_house();
                    player.addMoney((int) (((Deed) map.getMap().get(player.getIndex())).getPrice() * -0.5));
                } else if (((Deed) map.getMap().get(player.getIndex())).getHouse() == 4) {
                    buyButt.setText("Buy Hotel");
                    ((Deed) map.getMap().get(player.getIndex())).add_hotel();
                    player.addMoney((int) (((Deed) map.getMap().get(player.getIndex())).getPrice() * -0.5));
                }
            }

        } else if (map.getMap().get(player.getIndex()).getClass() == Station.class) {
            if (map.getMap().get(player.getIndex()).getOwner_name() == "None") {
                buyButt.setText("Buy");
                SubDeed.add(map.getMap().get(player.getIndex()).getDeed_panel());
                ((Station) map.getMap().get(player.getIndex())).setOwner(player);
                ((Station) map.getMap().get(player.getIndex())).setOwner_name(player.getName());
                ((Station) map.getMap().get(player.getIndex())).setBought(true);
                player.addMoney(((Station) map.getMap().get(player.getIndex())).getPrice() * -1);
                player.getStation().add((Station) map.getMap().get(player.getIndex()));
            }
        }
        SubDeed.validate();
        SubDeed.repaint();
        DeedPanel.validate();
        DeedPanel.repaint();
        MoneyPanel.setText(String.valueOf("$" + player.getMoney()));
    }//GEN-LAST:event_buyButtActionPerformed

    private void sellButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtActionPerformed
        // TODO add your handling code here:

        System.out.println(player.getIndex());
        if (player.sell(map.getMap().get(player.getIndex())) && !(map.getSpecial().contains(player.getIndex()))) {
            for (Component i : SubDeed.getComponents()) {
                if (i == map.getMap().get(player.getIndex()).getDeed_panel()) {
                    SubDeed.remove(i);
                    break;
                }
            }
            SubDeed.validate();
            SubDeed.repaint();
            DeedPanel.validate();
            DeedPanel.repaint();
            MoneyPanel.setText(String.valueOf("$" + player.getMoney()));
        }

    }//GEN-LAST:event_sellButtActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        ((JLayeredPane) BoardPanel.getComponent(player.getIndex())).remove(player.getPanel());//*

        Random rand = new Random();
        int n = rand.nextInt(6) + 1;
        int n1 = rand.nextInt(6) + 1;

        Thread t = new Thread(new Runnable() {
            int i = 0;

            @Override
            public void run() {
                int n2 = rand.nextInt(6) + 1;
                for (i = 0; i < 15; i++) {
                    n2 = rand.nextInt(6) + 1;
                    dice1.setIcon(imgSet[n2 - 1]);

                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        System.out.println("");
                    }

                }
                dice1.setIcon(imgSet[n - 1]);
            }

        });
        Thread t1 = new Thread(new Runnable() {
            int j = 0;

            @Override
            public void run() {
                int n3 = rand.nextInt(6) + 1;
                while (j < 15) {
                    n3 = rand.nextInt(6) + 1;
                    dice2.setIcon(imgSet[n3 - 1]);
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        System.out.println("");
                    }
                    j++;

                }
                map.getMap().get(player.getIndex()).getMap_panel().validate();
                map.getMap().get(player.getIndex()).getMap_panel().repaint();
                dice2.setIcon(imgSet[n1 - 1]);
                player.walk(10);
                map.getMap().get(player.getIndex()).action(player); 
                ((JLayeredPane) BoardPanel.getComponent(player.getIndex())).add(player.getPanel(), JLayeredPane.DRAG_LAYER);//*
                map.getMap().get(player.getIndex()).getMap_panel().validate();
                map.getMap().get(player.getIndex()).getMap_panel().repaint();
                System.out.println(player.getIndex());
                MoneyPanel.setText("" + player.getMoney());

            }

        });
        t.start();
        t1.start();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLayeredPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane7MouseClicked

    }//GEN-LAST:event_jLayeredPane7MouseClicked

    private void jLayeredPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseClicked
    
    }//GEN-LAST:event_jLayeredPane5MouseClicked

    private void GoldenGateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoldenGateMouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/goldengatebeidge.png")));
        popup.setTitle("Owner: " + map.getMap().get(29).getOwner_name());
        popup.setVisible(true);

    }//GEN-LAST:event_GoldenGateMouseClicked

    private void HollywoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HollywoodMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/Hollywood.png")));
        popup.setTitle("Owner: " + map.getMap().get(27).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_HollywoodMouseClicked

    private void Gateway_of_ArchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gateway_of_ArchMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/gateway.png")));
        popup.setTitle("Owner: " + map.getMap().get(8).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Gateway_of_ArchMouseClicked

    private void JacobFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JacobFieldMouseClicked

       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/jacobfield.png")));
        popup.setTitle("Owner: " + map.getMap().get(1).getOwner_name());
        popup.setVisible(true);
        
    }//GEN-LAST:event_JacobFieldMouseClicked

    private void Chest1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chest1MouseClicked

        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chest.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chest1MouseClicked

    private void TexasStadiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TexasStadiumMouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/texasstadium.png")));
        popup.setTitle("Owner: " + map.getMap().get(3).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_TexasStadiumMouseClicked

    private void TaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaxMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/TAX.png")));
        popup.setTitle("Owner: " + map.getMap().get(4).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_TaxMouseClicked

    private void ORDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORDMouseClicked

       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/ORD_AIRPORT.png")));
        popup.setTitle("Owner: " + map.getMap().get(5).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_ORDMouseClicked

    private void Grand_Ole_OpryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grand_Ole_OpryMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/grand_ole_opry.png")));
        popup.setTitle("Owner: " + map.getMap().get(6).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Grand_Ole_OpryMouseClicked

    private void Chance1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chance1MouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chance.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chance1MouseClicked

    private void Mall_of_AmericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mall_of_AmericaMouseClicked


        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/mallofamerica.png")));
        popup.setTitle("Owner: " + map.getMap().get(9).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Mall_of_AmericaMouseClicked

    private void VisitingJailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitingJailMouseClicked

        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/jail.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_VisitingJailMouseClicked

    private void Olympic_ParkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Olympic_ParkMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/olympic_park.png")));
        popup.setTitle("Owner: " + map.getMap().get(11).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Olympic_ParkMouseClicked

    private void Mobile_ServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mobile_ServiceMouseClicked
        // TODO add your handling code here:
        //JLabel picture = new JLabel();
        //ImageIcon image = new ImageIcon(getClass().getResource("/Pic/boardDeeds/MIGHTY_MOBILE.png"));
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/MIGHTY_MOBILE.png")));
       
       popup.setTitle("Owner: " + map.getMap().get(12).getOwner_name());
        popup.setVisible(true);;
    }//GEN-LAST:event_Mobile_ServiceMouseClicked

    private void Red_RocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Red_RocksMouseClicked

        //JLabel picture = new JLabel();
        //ImageIcon image = new ImageIcon(getClass().getResource("/Pic/boardDeeds/redrocks.png"));
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/redrocks.png")));
        //popup.add(picture, BorderLayout.CENTER);
        popup.setTitle("Owner: " + map.getMap().get(13).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Red_RocksMouseClicked

    private void Liberty_BellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Liberty_BellMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/libertybell.png")));
        popup.setTitle("Owner: " + map.getMap().get(14).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Liberty_BellMouseClicked

    private void LAXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAXMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/LAX_AIRPORT.png")));
        popup.setTitle("Owner: " + map.getMap().get(15).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_LAXMouseClicked

    private void South_BeachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_South_BeachMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/southbeach.png")));
        popup.setTitle("Owner: " + map.getMap().get(16).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_South_BeachMouseClicked

    private void Chest2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chest2MouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chest.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chest2MouseClicked

    private void JohnsonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JohnsonMouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/johnson.png")));
        popup.setTitle("Owner: " + map.getMap().get(18).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_JohnsonMouseClicked

    private void Pioneer_SquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pioneer_SquareMouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/pioneer_square.png")));
        popup.setTitle("Owner: " + map.getMap().get(19).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Pioneer_SquareMouseClicked

    private void CamelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamelBackMouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/cameback.png")));
        popup.setTitle("Owner: " + map.getMap().get(21).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_CamelBackMouseClicked

    private void Chance2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chance2MouseClicked
        // TODO add your handling code here:
       pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chance.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chance2MouseClicked

    private void WaikikiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaikikiMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/waikiki_beach.png")));
        popup.setTitle("Owner: " + map.getMap().get(23).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_WaikikiMouseClicked

    private void DisneyWorldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisneyWorldMouseClicked
        // TODO add your handling code here:
      
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/disneyworld.png")));
        popup.setTitle("Owner: " + map.getMap().get(24).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_DisneyWorldMouseClicked

    private void JFKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JFKMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/JFK_AIRPORT.png")));
        popup.setTitle("Owner: " + map.getMap().get(25).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_JFKMouseClicked

    private void French_QuarterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_French_QuarterMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/frechquarter.png")));
        popup.setTitle("Owner: " + map.getMap().get(26).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_French_QuarterMouseClicked

    private void Internet_ServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Internet_ServiceMouseClicked

        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/MIGHTY_FIBRE.png")));
        popup.setTitle("Owner: " + map.getMap().get(28).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Internet_ServiceMouseClicked

    private void LasVegasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LasVegasMouseClicked
 
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/lasvegas.png")));
        popup.setTitle("Owner: " + map.getMap().get(31).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_LasVegasMouseClicked

    private void Wrigley_FieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wrigley_FieldMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/wrigley field.png")));
        popup.setTitle("Owner: " + map.getMap().get(32).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Wrigley_FieldMouseClicked

    private void Chest3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chest3MouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chest.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chest3MouseClicked

    private void White_HouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_White_HouseMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/whitehouse.png")));
        popup.setTitle("Owner: " + map.getMap().get(34).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_White_HouseMouseClicked

    private void ATLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATLMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/ATL_AIRPORT.png")));
        popup.setTitle("Owner: " + map.getMap().get(35).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_ATLMouseClicked

    private void Chance3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chance3MouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/chance.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Chance3MouseClicked

    private void Fenway_ParkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fenway_ParkMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/fenwaypark.png")));
        popup.setTitle("Owner: " + map.getMap().get(37).getOwner_name());      
        popup.setVisible(true);
    }//GEN-LAST:event_Fenway_ParkMouseClicked

    private void Credit_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Credit_CardMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_Credit_CardMouseEntered

    private void Credit_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Credit_CardMouseClicked
        // TODO add your handling code here:
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/CREDITCARDDEBT.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Credit_CardMouseClicked

    private void Time_SquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Time_SquareMouseClicked

        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/time_square.png")));
        popup.setTitle("Owner: " + map.getMap().get(39).getOwner_name());
        popup.setVisible(true);
    }//GEN-LAST:event_Time_SquareMouseClicked

    private void Go_StartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Go_StartMouseClicked
       
         pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/GO.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Go_StartMouseClicked

    private void Free_ParkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Free_ParkingMouseClicked
        // TODO add your handling code here: 
        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/parking.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_Free_ParkingMouseClicked

    private void GoToJailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToJailMouseClicked

        pic.setIcon(new ImageIcon(getClass().getResource("/Pic/boardDeeds/gojail.png")));
        popup.setVisible(true);
    }//GEN-LAST:event_GoToJailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        Player p = new Player("Chai", "/Pic/1.png", 2000000);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(p
                ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATL;
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JPanel CamelBack;
    private javax.swing.JPanel Chance1;
    private javax.swing.JPanel Chance2;
    private javax.swing.JPanel Chance3;
    private javax.swing.JPanel Chest1;
    private javax.swing.JPanel Chest2;
    private javax.swing.JPanel Chest3;
    private javax.swing.JPanel Credit_Card;
    private javax.swing.JPanel DeedPanel;
    private javax.swing.JPanel DisneyWorld;
    private javax.swing.JPanel Fenway_Park;
    private javax.swing.JPanel Free_Parking;
    private javax.swing.JPanel French_Quarter;
    private javax.swing.JPanel Gateway_of_Arch;
    private javax.swing.JPanel GoToJail;
    private javax.swing.JPanel Go_Start;
    private javax.swing.JPanel GoldenGate;
    private javax.swing.JPanel Grand_Ole_Opry;
    private javax.swing.JPanel Hollywood;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel Internet_Service;
    private javax.swing.JPanel JFK;
    private javax.swing.JPanel JacobField;
    private javax.swing.JPanel Johnson;
    private javax.swing.JPanel LAX;
    private javax.swing.JPanel LasVegas;
    private javax.swing.JPanel Liberty_Bell;
    private javax.swing.JPanel Mall_of_America;
    private javax.swing.JPanel Mobile_Service;
    private javax.swing.JTextField MoneyPanel;
    private javax.swing.JPanel ORD;
    private javax.swing.JPanel Olympic_Park;
    private javax.swing.JPanel Pioneer_Square;
    private javax.swing.JPanel Red_Rocks;
    private javax.swing.JPanel South_Beach;
    private javax.swing.JPanel SubDeed;
    private javax.swing.JPanel Tax;
    private javax.swing.JPanel TexasStadium;
    private javax.swing.JPanel Time_Square;
    private javax.swing.JPanel VisitingJail;
    private javax.swing.JPanel Waikiki;
    private javax.swing.JPanel White_House;
    private javax.swing.JPanel Wrigley_Field;
    private javax.swing.JButton buyButt;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JLayeredPane jLayeredPane12;
    private javax.swing.JLayeredPane jLayeredPane13;
    private javax.swing.JLayeredPane jLayeredPane14;
    private javax.swing.JLayeredPane jLayeredPane15;
    private javax.swing.JLayeredPane jLayeredPane16;
    private javax.swing.JLayeredPane jLayeredPane17;
    private javax.swing.JLayeredPane jLayeredPane18;
    private javax.swing.JLayeredPane jLayeredPane19;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane20;
    private javax.swing.JLayeredPane jLayeredPane21;
    private javax.swing.JLayeredPane jLayeredPane22;
    private javax.swing.JLayeredPane jLayeredPane23;
    private javax.swing.JLayeredPane jLayeredPane24;
    private javax.swing.JLayeredPane jLayeredPane25;
    private javax.swing.JLayeredPane jLayeredPane26;
    private javax.swing.JLayeredPane jLayeredPane27;
    private javax.swing.JLayeredPane jLayeredPane28;
    private javax.swing.JLayeredPane jLayeredPane29;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane30;
    private javax.swing.JLayeredPane jLayeredPane31;
    private javax.swing.JLayeredPane jLayeredPane32;
    private javax.swing.JLayeredPane jLayeredPane33;
    private javax.swing.JLayeredPane jLayeredPane34;
    private javax.swing.JLayeredPane jLayeredPane35;
    private javax.swing.JLayeredPane jLayeredPane36;
    private javax.swing.JLayeredPane jLayeredPane37;
    private javax.swing.JLayeredPane jLayeredPane38;
    private javax.swing.JLayeredPane jLayeredPane39;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane40;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JDialog noMoneyDialog;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel pic;
    private javax.swing.JDialog popup;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JButton sellButt;
    // End of variables declaration//GEN-END:variables
}
