/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopony;

import javafx.scene.paint.Color;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Supachai
 */
public class ReadyF extends javax.swing.JFrame {

    String p_img;
    Player ready_p;
    Main obj_m;

    /**
     * Creates new form ReadyF
     */
    public ReadyF() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ready_p = new Player("get name from database", "/Pic/Elon.png", 2000000);
        obj_m = new Main(ready_p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        green = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();
        yellow = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        readyb = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 735));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 735));
        jPanel1.setLayout(null);

        green.setBackground(new java.awt.Color(255, 255, 255));
        green.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/oprah.jpg"))); // NOI18N
        green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                greenMousePressed(evt);
            }
        });
        jPanel1.add(green);
        green.setBounds(520, 410, 166, 150);

        blue.setBackground(new java.awt.Color(255, 255, 255));
        blue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/mark.jpg"))); // NOI18N
        blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                blueMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueMouseClicked(evt);
            }
        });
        jPanel1.add(blue);
        blue.setBounds(700, 410, 166, 150);

        yellow.setBackground(new java.awt.Color(255, 255, 255));
        yellow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Elon.jpg"))); // NOI18N
        yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yellowMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowMouseClicked(evt);
            }
        });
        jPanel1.add(yellow);
        yellow.setBounds(880, 410, 166, 150);

        red.setBackground(new java.awt.Color(255, 255, 255));
        red.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/tony.jpg"))); // NOI18N
        red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                redMousePressed(evt);
            }
        });
        jPanel1.add(red);
        red.setBounds(340, 410, 166, 150);

        readyb.setText("Ready");
        readyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readybActionPerformed(evt);
            }
        });
        jPanel1.add(readyb);
        readyb.setBounds(1157, 207, 81, 29);
        jPanel1.add(show);
        show.setBounds(470, 10, 480, 343);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ReadyBG.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1370, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseClicked
        // TODO add your handling code here: 
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/tonyShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);


    }//GEN-LAST:event_redMouseClicked

    private void greenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenMouseClicked
        // TODO add your handling code here: 
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/oprahShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
    }//GEN-LAST:event_greenMouseClicked

    private void blueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueMouseClicked
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/markShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
    }//GEN-LAST:event_blueMouseClicked

    private void yellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseClicked
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/ElonShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
    }//GEN-LAST:event_yellowMouseClicked

    private void redMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMousePressed
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/tonyShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
        p_img = "/Pic/tony.jpg";
    }//GEN-LAST:event_redMousePressed

    private void greenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenMousePressed
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/oprahShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
        p_img = "/Pic/oprah.jpg";
    }//GEN-LAST:event_greenMousePressed

    private void blueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueMousePressed
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/markShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
        p_img = "/Pic/mark.jpg";
    }//GEN-LAST:event_blueMousePressed

    private void yellowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMousePressed
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon(getClass().getResource("/Pic/ElonShow.jpg"));
        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setHorizontalAlignment(JLabel.CENTER);
        show.setIcon(ic);
        p_img = "/Pic/Elon.jpg";
    }//GEN-LAST:event_yellowMousePressed

    private void readybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readybActionPerformed
        // TODO add your handling code here: 
        ready_p.setPath(p_img);
        ready_p.setLabelImage(p_img);

    }//GEN-LAST:event_readybActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadyF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadyF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadyF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadyF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadyF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blue;
    private javax.swing.JLabel green;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton readyb;
    private javax.swing.JLabel red;
    private javax.swing.JLabel show;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
