/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopony;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Font;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author visio
 */
public class Main extends javax.swing.JFrame {

    private Map map;
    private Player player;
    private Player player2;
    private ArrayList<JPanel> boardBlocks;
    private ImageIcon default_img = new ImageIcon("C:\\Users\\visio\\Documents\\NetBeansProjects\\Monopony\\src\\Pic\\d0.png");
    ;
    private ImageIcon img1 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d1.png");
    private ImageIcon img2 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d2.png");
    private ImageIcon img3 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d3.png");
    private ImageIcon img4 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d4.png");
    private ImageIcon img5 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d5.png");
    private ImageIcon img6 = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopony\\src\\Pic\\d6.png");
    private ImageIcon[] imgSet = {img1, img2, img3, img4, img5, img6};

    /**
     * Creates new form Main
     */
    public Main() {
        player = new Player("Pym", "/Pic/1.png", 500);
        player2 = new Player("Chai","/Pic/1.png",500);
        this.setAlwaysOnTop(true);
        map = new Map();
        initComponents();
        MoneyPanel.setText("$" + player.getMoney());
        ((Deed) map.getMap().get(27)).setOwner(player2);
        ((Deed) map.getMap().get(27)).setOwner_name(player2.getName());
        ((Deed) map.getMap().get(27)).setBought(true);
        ((Deed) map.getMap().get(26)).setOwner(player);
        ((Deed) map.getMap().get(26)).setOwner_name(player.getName());
        ((Deed) map.getMap().get(26)).setBought(true);
        //for(int i = 0; i<39;i++){
        //BoardPanel.getComponent(0).setBackground(Color.red);
        //}
        //jLayeredPane1.add(player.getPanel(),JLayeredPane.DRAG_LAYER);
        //jPanel24.validate();
        //jPanel24.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noMoneyDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        sellDialog = new javax.swing.JDialog();
        DeedPanel = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        SubDeed = new javax.swing.JPanel();
        BoardPanel = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jPanel21 = map.getMap().get(0).getMap_panel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jPanel22 = map.getMap().get(1).getMap_panel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jPanel23 = map.getMap().get(2).getMap_panel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel24 = map.getMap().get(3).getMap_panel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jPanel25 = map.getMap().get(4).getMap_panel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel26 = map.getMap().get(5).getMap_panel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jPanel27 = map.getMap().get(6).getMap_panel();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        jPanel28 = map.getMap().get(7).getMap_panel();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        jPanel29 = map.getMap().get(8).getMap_panel();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        jPanel30 = map.getMap().get(9).getMap_panel();
        jLayeredPane12 = new javax.swing.JLayeredPane();
        jPanel31 = map.getMap().get(10).getMap_panel();
        jLayeredPane13 = new javax.swing.JLayeredPane();
        jPanel32 = map.getMap().get(11).getMap_panel();
        jLayeredPane14 = new javax.swing.JLayeredPane();
        jPanel33 = map.getMap().get(12).getMap_panel();
        jLayeredPane15 = new javax.swing.JLayeredPane();
        jPanel34 = map.getMap().get(13).getMap_panel();
        jLayeredPane16 = new javax.swing.JLayeredPane();
        jPanel35 = map.getMap().get(14).getMap_panel();
        jLayeredPane17 = new javax.swing.JLayeredPane();
        jPanel36 = map.getMap().get(15).getMap_panel();
        jLayeredPane18 = new javax.swing.JLayeredPane();
        jPanel37 = map.getMap().get(16).getMap_panel();
        jLayeredPane19 = new javax.swing.JLayeredPane();
        jPanel38 = map.getMap().get(17).getMap_panel();
        jLayeredPane20 = new javax.swing.JLayeredPane();
        jPanel39 = map.getMap().get(18).getMap_panel();
        jLayeredPane21 = new javax.swing.JLayeredPane();
        jPanel40 = map.getMap().get(19).getMap_panel();
        jLayeredPane22 = new javax.swing.JLayeredPane();
        jPanel1 = map.getMap().get(20).getMap_panel();
        jLayeredPane23 = new javax.swing.JLayeredPane();
        jPanel2 = map.getMap().get(21).getMap_panel();
        jLayeredPane24 = new javax.swing.JLayeredPane();
        jPanel3 = map.getMap().get(22).getMap_panel();
        jLayeredPane25 = new javax.swing.JLayeredPane();
        jPanel4 = map.getMap().get(23).getMap_panel();
        jLayeredPane26 = new javax.swing.JLayeredPane();
        jPanel5 = map.getMap().get(24).getMap_panel();
        jLayeredPane27 = new javax.swing.JLayeredPane();
        jPanel6 = map.getMap().get(25).getMap_panel();
        jLayeredPane28 = new javax.swing.JLayeredPane();
        jPanel7 = map.getMap().get(26).getMap_panel();
        jLayeredPane29 = new javax.swing.JLayeredPane();
        jPanel8 = map.getMap().get(27).getMap_panel();
        jLayeredPane30 = new javax.swing.JLayeredPane();
        jPanel9 = map.getMap().get(28).getMap_panel();
        jLayeredPane31 = new javax.swing.JLayeredPane();
        jPanel10 = map.getMap().get(29).getMap_panel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel11 = map.getMap().get(30).getMap_panel();
        jLayeredPane32 = new javax.swing.JLayeredPane();
        jPanel12 = map.getMap().get(31).getMap_panel();
        jLayeredPane33 = new javax.swing.JLayeredPane();
        jPanel13 = map.getMap().get(32).getMap_panel();
        jLayeredPane34 = new javax.swing.JLayeredPane();
        jPanel14 = map.getMap().get(33).getMap_panel();
        jLayeredPane35 = new javax.swing.JLayeredPane();
        jPanel15 = map.getMap().get(34).getMap_panel();
        jLayeredPane36 = new javax.swing.JLayeredPane();
        jPanel16 = map.getMap().get(35).getMap_panel();
        jLayeredPane37 = new javax.swing.JLayeredPane();
        jPanel17 = map.getMap().get(36).getMap_panel();
        jLayeredPane38 = new javax.swing.JLayeredPane();
        jPanel18 = map.getMap().get(37).getMap_panel();
        jLayeredPane39 = new javax.swing.JLayeredPane();
        jPanel19 = map.getMap().get(38).getMap_panel();
        jLayeredPane40 = new javax.swing.JLayeredPane();
        jPanel20 = map.getMap().get(39).getMap_panel();
        jPanel41 = new javax.swing.JPanel();
        InfoPanel = new javax.swing.JPanel();
        MoneyPanel = new javax.swing.JTextField();
        buyButt = new javax.swing.JButton();
        sellButt = new javax.swing.JButton();
        owner = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();

        noMoneyDialog.setLocation(new java.awt.Point(1000, 500));
        noMoneyDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        noMoneyDialog.setPreferredSize(new java.awt.Dimension(286, 120));
        noMoneyDialog.setResizable(false);
        noMoneyDialog.setSize(new java.awt.Dimension(286, 120));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("You don't have enough money");

        javax.swing.GroupLayout noMoneyDialogLayout = new javax.swing.GroupLayout(noMoneyDialog.getContentPane());
        noMoneyDialog.getContentPane().setLayout(noMoneyDialogLayout);
        noMoneyDialogLayout.setHorizontalGroup(
            noMoneyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        noMoneyDialogLayout.setVerticalGroup(
            noMoneyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout sellDialogLayout = new javax.swing.GroupLayout(sellDialog.getContentPane());
        sellDialog.getContentPane().setLayout(sellDialogLayout);
        sellDialogLayout.setHorizontalGroup(
            sellDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        sellDialogLayout.setVerticalGroup(
            sellDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        DeedPanel.setBackground(new java.awt.Color(51, 51, 51));
        DeedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 10));
        DeedPanel.setPreferredSize(new java.awt.Dimension(350, 900));

        scrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        scrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane1.setMinimumSize(new java.awt.Dimension(350, 900));

        SubDeed.setBackground(new java.awt.Color(54, 185, 148));
        SubDeed.setLayout(new java.awt.GridLayout(20, 1));
        scrollPane1.add(SubDeed);

        javax.swing.GroupLayout DeedPanelLayout = new javax.swing.GroupLayout(DeedPanel);
        DeedPanel.setLayout(DeedPanelLayout);
        DeedPanelLayout.setHorizontalGroup(
            DeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeedPanelLayout.setVerticalGroup(
            DeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(DeedPanel);

        BoardPanel.setBackground(new java.awt.Color(51, 51, 51));
        BoardPanel.setMinimumSize(new java.awt.Dimension(880, 900));
        BoardPanel.setPreferredSize(new java.awt.Dimension(880, 900));
        BoardPanel.setLayout(null);

        jLayeredPane4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 100));
        jLayeredPane4.add(jPanel21);
        jPanel21.getAccessibleContext().setAccessibleName("1");

        BoardPanel.add(jLayeredPane4);
        jLayeredPane4.setBounds(760, 740, 110, 120);

        jLayeredPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseClicked(evt);
            }
        });

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel22.setPreferredSize(new java.awt.Dimension(70, 100));

        jLayeredPane5.setLayer(jPanel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BoardPanel.add(jLayeredPane5);
        jLayeredPane5.setBounds(680, 740, 80, 120);

        jLayeredPane6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel23.setPreferredSize(new java.awt.Dimension(70, 100));
        jLayeredPane6.add(jPanel23);

        BoardPanel.add(jLayeredPane6);
        jLayeredPane6.setBounds(620, 740, 60, 120);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 5));

        jPanel24.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel24.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane1.add(jPanel24);
        jPanel24.setBounds(5, 5, 60, 110);

        BoardPanel.add(jLayeredPane1);
        jLayeredPane1.setBounds(550, 740, 70, 120);

        jLayeredPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane7MouseClicked(evt);
            }
        });
        jLayeredPane7.setLayout(new java.awt.GridLayout(1, 0));

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel25.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel25.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane7.add(jPanel25);

        BoardPanel.add(jLayeredPane7);
        jLayeredPane7.setBounds(480, 740, 70, 120);

        jLayeredPane3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel26.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel26.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane3.add(jPanel26);

        BoardPanel.add(jLayeredPane3);
        jLayeredPane3.setBounds(410, 740, 70, 120);

        jLayeredPane8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel27.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel27.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane8.add(jPanel27);

        BoardPanel.add(jLayeredPane8);
        jLayeredPane8.setBounds(340, 740, 70, 120);

        jLayeredPane9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel28.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel28.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane9.add(jPanel28);

        BoardPanel.add(jLayeredPane9);
        jLayeredPane9.setBounds(270, 740, 70, 120);

        jLayeredPane10.setLayout(new java.awt.GridLayout(1, 0));

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel29.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel29MouseClicked(evt);
            }
        });
        jPanel29.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane10.add(jPanel29);

        BoardPanel.add(jLayeredPane10);
        jLayeredPane10.setBounds(200, 740, 70, 120);

        jLayeredPane11.setLayout(new java.awt.GridLayout(1, 0));

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel30.setPreferredSize(new java.awt.Dimension(70, 100));
        jPanel30.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane11.add(jPanel30);

        BoardPanel.add(jLayeredPane11);
        jLayeredPane11.setBounds(130, 740, 70, 120);

        jLayeredPane12.setLayout(new java.awt.GridLayout(1, 0));

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel31.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel31.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane12.add(jPanel31);
        jPanel31.getAccessibleContext().setAccessibleName("10");

        BoardPanel.add(jLayeredPane12);
        jLayeredPane12.setBounds(10, 740, 120, 120);

        jLayeredPane13.setLayout(new java.awt.GridLayout(1, 0));

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel32.setForeground(new java.awt.Color(0, 204, 204));
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel32.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane13.add(jPanel32);

        BoardPanel.add(jLayeredPane13);
        jLayeredPane13.setBounds(10, 680, 120, 60);

        jLayeredPane14.setLayout(new java.awt.GridLayout(1, 0));

        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel33.setForeground(new java.awt.Color(0, 204, 204));
        jPanel33.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel33.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane14.add(jPanel33);

        BoardPanel.add(jLayeredPane14);
        jLayeredPane14.setBounds(10, 610, 120, 70);

        jLayeredPane15.setLayout(new java.awt.GridLayout(1, 0));

        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel34.setForeground(new java.awt.Color(0, 204, 204));
        jPanel34.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel34.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane15.add(jPanel34);

        BoardPanel.add(jLayeredPane15);
        jLayeredPane15.setBounds(10, 540, 120, 70);

        jLayeredPane16.setLayout(new java.awt.GridLayout(1, 0));

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel35.setForeground(new java.awt.Color(0, 204, 204));
        jPanel35.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel35.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane16.add(jPanel35);

        BoardPanel.add(jLayeredPane16);
        jLayeredPane16.setBounds(10, 470, 120, 70);

        jLayeredPane17.setLayout(new java.awt.GridLayout(1, 0));

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel36.setForeground(new java.awt.Color(0, 204, 204));
        jPanel36.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel36.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane17.add(jPanel36);

        BoardPanel.add(jLayeredPane17);
        jLayeredPane17.setBounds(10, 400, 120, 70);

        jLayeredPane18.setLayout(new java.awt.GridLayout(1, 0));

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel37.setForeground(new java.awt.Color(0, 204, 204));
        jPanel37.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel37.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane18.add(jPanel37);

        BoardPanel.add(jLayeredPane18);
        jLayeredPane18.setBounds(10, 330, 120, 70);

        jLayeredPane19.setLayout(new java.awt.GridLayout(1, 0));

        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel38.setForeground(new java.awt.Color(0, 204, 204));
        jPanel38.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel38.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane19.add(jPanel38);

        BoardPanel.add(jLayeredPane19);
        jLayeredPane19.setBounds(10, 260, 120, 70);

        jLayeredPane20.setLayout(new java.awt.GridLayout(1, 0));

        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel39.setForeground(new java.awt.Color(0, 204, 204));
        jPanel39.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel39.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane20.add(jPanel39);

        BoardPanel.add(jLayeredPane20);
        jLayeredPane20.setBounds(10, 190, 120, 70);

        jLayeredPane21.setLayout(new java.awt.GridLayout(1, 0));

        jPanel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel40.setForeground(new java.awt.Color(0, 204, 204));
        jPanel40.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel40.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane21.add(jPanel40);

        BoardPanel.add(jLayeredPane21);
        jLayeredPane21.setBounds(10, 120, 120, 70);

        jLayeredPane22.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane22.add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("30");
        jPanel1.getAccessibleContext().setAccessibleDescription("Ded");

        BoardPanel.add(jLayeredPane22);
        jLayeredPane22.setBounds(10, 10, 120, 110);

        jLayeredPane23.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane23.add(jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("");

        BoardPanel.add(jLayeredPane23);
        jLayeredPane23.setBounds(130, 10, 70, 110);

        jLayeredPane24.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel3.setForeground(new java.awt.Color(0, 204, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane24.add(jPanel3);

        BoardPanel.add(jLayeredPane24);
        jLayeredPane24.setBounds(200, 10, 70, 110);

        jLayeredPane25.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane25.add(jPanel4);

        BoardPanel.add(jLayeredPane25);
        jLayeredPane25.setBounds(270, 10, 70, 110);

        jLayeredPane26.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel5.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane26.add(jPanel5);

        BoardPanel.add(jLayeredPane26);
        jLayeredPane26.setBounds(340, 10, 70, 110);

        jLayeredPane27.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel6.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane27.add(jPanel6);

        BoardPanel.add(jLayeredPane27);
        jLayeredPane27.setBounds(410, 10, 70, 110);

        jLayeredPane28.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel7.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane28.add(jPanel7);

        BoardPanel.add(jLayeredPane28);
        jLayeredPane28.setBounds(480, 10, 70, 110);

        jLayeredPane29.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel8.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane29.add(jPanel8);

        BoardPanel.add(jLayeredPane29);
        jLayeredPane29.setBounds(550, 10, 70, 110);

        jLayeredPane30.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel9.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane30.add(jPanel9);

        BoardPanel.add(jLayeredPane30);
        jLayeredPane30.setBounds(620, 10, 70, 110);

        jLayeredPane31.setLayout(new java.awt.GridLayout(1, 0));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel10.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane31.add(jPanel10);

        BoardPanel.add(jLayeredPane31);
        jLayeredPane31.setBounds(690, 10, 70, 110);

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane2.add(jPanel11);
        jPanel11.getAccessibleContext().setAccessibleName("");

        BoardPanel.add(jLayeredPane2);
        jLayeredPane2.setBounds(760, 10, 110, 110);

        jLayeredPane32.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane32.add(jPanel12);

        BoardPanel.add(jLayeredPane32);
        jLayeredPane32.setBounds(760, 120, 110, 70);

        jLayeredPane33.setLayout(new java.awt.GridLayout(1, 0));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane33.add(jPanel13);

        BoardPanel.add(jLayeredPane33);
        jLayeredPane33.setBounds(760, 190, 110, 70);

        jLayeredPane34.setLayout(new java.awt.GridLayout(1, 0));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane34.add(jPanel14);

        BoardPanel.add(jLayeredPane34);
        jLayeredPane34.setBounds(760, 260, 110, 70);

        jLayeredPane35.setLayout(new java.awt.GridLayout(1, 0));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane35.add(jPanel15);

        BoardPanel.add(jLayeredPane35);
        jLayeredPane35.setBounds(760, 330, 110, 70);

        jLayeredPane36.setLayout(new java.awt.GridLayout(1, 0));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel16.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane36.add(jPanel16);

        BoardPanel.add(jLayeredPane36);
        jLayeredPane36.setBounds(760, 400, 110, 70);

        jLayeredPane37.setLayout(new java.awt.GridLayout(1, 0));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane37.add(jPanel17);

        BoardPanel.add(jLayeredPane37);
        jLayeredPane37.setBounds(760, 470, 110, 70);

        jLayeredPane38.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel18.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane38.add(jPanel18);

        BoardPanel.add(jLayeredPane38);
        jLayeredPane38.setBounds(760, 540, 110, 70);

        jLayeredPane39.setLayout(new java.awt.GridLayout(1, 0));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));
        jLayeredPane39.add(jPanel19);

        BoardPanel.add(jLayeredPane39);
        jLayeredPane39.setBounds(760, 610, 110, 70);

        jLayeredPane40.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 185, 148), 3));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel20.setLayout(new java.awt.GridLayout(1, 1));
        jLayeredPane40.add(jPanel20);

        BoardPanel.add(jLayeredPane40);
        jLayeredPane40.setBounds(760, 680, 110, 60);

        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 5));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        BoardPanel.add(jPanel41);
        jPanel41.setBounds(130, 120, 630, 620);

        getContentPane().add(BoardPanel);

        InfoPanel.setBackground(new java.awt.Color(51, 51, 51));

        MoneyPanel.setEditable(false);
        MoneyPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyPanelActionPerformed(evt);
            }
        });

        buyButt.setText("BUY");
        buyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtActionPerformed(evt);
            }
        });

        sellButt.setText("SELL");
        sellButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtActionPerformed(evt);
            }
        });

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        jButton3.setText("Roll");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dice1.setIcon(default_img);

        dice2.setIcon(default_img);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoneyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(InfoPanelLayout.createSequentialGroup()
                                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(InfoPanelLayout.createSequentialGroup()
                                    .addComponent(buyButt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sellButt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MoneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyButt, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(sellButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        getContentPane().add(InfoPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoneyPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyPanelActionPerformed

    private void buyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtActionPerformed
        // TODO add your handling code here:
        System.out.println(player.getIndex());
        if (player.getMoney() < map.getMap().get(player.getIndex()).getPrice()) {
            noMoneyDialog.setAlwaysOnTop(true);
            noMoneyDialog.setVisible(true);
            return;
        }
        if (map.getMap().get(player.getIndex()).getClass() == Deed.class) {
            if (map.getMap().get(player.getIndex()).getOwner_name() == "None") {
                buyButt.setText("Buy");
                SubDeed.add(map.getMap().get(player.getIndex()).getDeed_panel());
                ((Deed) map.getMap().get(player.getIndex())).setOwner(player);
                ((Deed) map.getMap().get(player.getIndex())).setOwner_name(player.getName());
                ((Deed) map.getMap().get(player.getIndex())).setBought(true);
                player.addMoney(((Deed) map.getMap().get(player.getIndex())).getPrice() * -1);
                player.getDeeds().add((Deed) map.getMap().get(player.getIndex()));
            }
            if (map.getMap().get(player.getIndex()).getOwner_name().equals(player.getName())) {
                if (((Deed) map.getMap().get(player.getIndex())).getHouse() >= 0 && ((Deed) map.getMap().get(player.getIndex())).getHouse() < 4 && ((Deed) map.getMap().get(player.getIndex())).isBought()) {
                    buyButt.setText("Buy House");
                    ((Deed) map.getMap().get(player.getIndex())).add_house();
                    player.addMoney((int) (((Deed) map.getMap().get(player.getIndex())).getPrice() * -0.5));
                } else if (((Deed) map.getMap().get(player.getIndex())).getHouse() == 4) {
                    buyButt.setText("Buy Hotel");
                    ((Deed) map.getMap().get(player.getIndex())).add_hotel();
                    player.addMoney((int) (((Deed) map.getMap().get(player.getIndex())).getPrice() * -0.5));
                }
            }

        } else if (map.getMap().get(player.getIndex()).getClass() == Station.class) {
            if (map.getMap().get(player.getIndex()).getOwner_name() == "None") {
                buyButt.setText("Buy");
                SubDeed.add(map.getMap().get(player.getIndex()).getDeed_panel());
                ((Station) map.getMap().get(player.getIndex())).setOwner(player);
                ((Station) map.getMap().get(player.getIndex())).setOwner_name(player.getName());
                ((Station) map.getMap().get(player.getIndex())).setBought(true);
                player.addMoney(((Station) map.getMap().get(player.getIndex())).getPrice() * -1);
                player.getStation().add((Station) map.getMap().get(player.getIndex()));
            }
        }
        SubDeed.validate();
        SubDeed.repaint();
        DeedPanel.validate();
        DeedPanel.repaint();
        MoneyPanel.setText(String.valueOf("$" + player.getMoney()));
    }//GEN-LAST:event_buyButtActionPerformed

    private void sellButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtActionPerformed
        // TODO add your handling code here:

        System.out.println(player.getIndex());
        if (player.sell(map.getMap().get(player.getIndex())) && !(map.getSpecial().contains(player.getIndex()))) {
            for (Component i : SubDeed.getComponents()) {
                if (i == map.getMap().get(player.getIndex()).getDeed_panel()) {
                    SubDeed.remove(i);
                    break;
                }
            }
            SubDeed.validate();
            SubDeed.repaint();
            DeedPanel.validate();
            DeedPanel.repaint();
            MoneyPanel.setText(String.valueOf("$" + player.getMoney()));
        }

    }//GEN-LAST:event_sellButtActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Random rand = new Random();
        int n = rand.nextInt(6) + 1;
        int n1 = rand.nextInt(6) + 1;

        Thread t = new Thread(new Runnable() {
            int i = 0;

            @Override
            public void run() {
                int n2 = rand.nextInt(6) + 1;
                for (i = 0; i < 15; i++) {
                    n2 = rand.nextInt(6) + 1;
                    dice1.setIcon(imgSet[n2 - 1]);

                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        System.out.println("");
                    }

                }
                dice1.setIcon(imgSet[n - 1]);
            }

        });
        Thread t1 = new Thread(new Runnable() {
            int j = 0;

            @Override
            public void run() {
                int n3 = rand.nextInt(6) + 1;
                while (j < 15) {
                    n3 = rand.nextInt(6) + 1;
                    dice2.setIcon(imgSet[n3 - 1]);
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        System.out.println("");
                    }
                    j++;

                }

                dice2.setIcon(imgSet[n1 - 1]);
                player.walk(27);
                map.getMap().get(player.getIndex()).action(player);
                map.getMap().get(player.getIndex()).getMap_panel().add(player.getPanel());
                map.getMap().get(player.getIndex()).getMap_panel().validate();
                map.getMap().get(player.getIndex()).getMap_panel().repaint();
                System.out.println(player.getIndex());
                MoneyPanel.setText("" + player.getMoney());

            }

        });
        t.start();
        t1.start();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLayeredPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLayeredPane7MouseClicked

    private void jLayeredPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseClicked
        // TODO add your handling code here:
        /*JDialog showCard = new JDialog();
        JLabel picture = new JLabel();
        ImageIcon image = new ImageIcon(card.get(index).getPic());
        picture.setIcon(image);
        showCard.setLayout(new BorderLayout());
        showCard.add(picture,BorderLayout.CENTER);
        showCard.setSize(291,197);
        showCard.setAlwaysOnTop(true);
        showCard.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        showCard.setLocation(650, 350);
        showCard.setVisible(true);*/
    }//GEN-LAST:event_jLayeredPane5MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        JDialog showCard = new JDialog();
        JLabel picture = new JLabel();
        ImageIcon image = new ImageIcon("D:\\NetBeans 8.1\\workspace\\Monopoly\\src\\Pic\\Hollywood.png");
        picture.setIcon(image);
        showCard.setLayout(new BorderLayout());
        showCard.add(picture, BorderLayout.CENTER);
        showCard.setSize(295, 360);
        showCard.setTitle("Owner: " + map.getMap().get(27).getOwner_name());
        showCard.setAlwaysOnTop(true);
        showCard.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        showCard.setLocation(650, 350);
        showCard.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel29MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JPanel DeedPanel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextField MoneyPanel;
    private javax.swing.JPanel SubDeed;
    private javax.swing.JButton buyButt;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JLayeredPane jLayeredPane12;
    private javax.swing.JLayeredPane jLayeredPane13;
    private javax.swing.JLayeredPane jLayeredPane14;
    private javax.swing.JLayeredPane jLayeredPane15;
    private javax.swing.JLayeredPane jLayeredPane16;
    private javax.swing.JLayeredPane jLayeredPane17;
    private javax.swing.JLayeredPane jLayeredPane18;
    private javax.swing.JLayeredPane jLayeredPane19;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane20;
    private javax.swing.JLayeredPane jLayeredPane21;
    private javax.swing.JLayeredPane jLayeredPane22;
    private javax.swing.JLayeredPane jLayeredPane23;
    private javax.swing.JLayeredPane jLayeredPane24;
    private javax.swing.JLayeredPane jLayeredPane25;
    private javax.swing.JLayeredPane jLayeredPane26;
    private javax.swing.JLayeredPane jLayeredPane27;
    private javax.swing.JLayeredPane jLayeredPane28;
    private javax.swing.JLayeredPane jLayeredPane29;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane30;
    private javax.swing.JLayeredPane jLayeredPane31;
    private javax.swing.JLayeredPane jLayeredPane32;
    private javax.swing.JLayeredPane jLayeredPane33;
    private javax.swing.JLayeredPane jLayeredPane34;
    private javax.swing.JLayeredPane jLayeredPane35;
    private javax.swing.JLayeredPane jLayeredPane36;
    private javax.swing.JLayeredPane jLayeredPane37;
    private javax.swing.JLayeredPane jLayeredPane38;
    private javax.swing.JLayeredPane jLayeredPane39;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane40;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JDialog noMoneyDialog;
    private javax.swing.JTextField owner;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JButton sellButt;
    private javax.swing.JDialog sellDialog;
    // End of variables declaration//GEN-END:variables
}
