/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopony;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Phustih
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form next
     */
    //public Mainmenu b = new Mainmenu();
    private JDBC jdbc;
    private Mainmenu b;
    public Register() throws SQLException {
        initComponents();
        jdbc = new JDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newUserLabel = new javax.swing.JLabel();
        newUser = new RoundJTextField(15);
        newPassLabel = new javax.swing.JLabel();
        repeatPassLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        newPass = new RoundJPasswordField(15);
        repeatPass = new RoundJPasswordField(15);
        name = new RoundJTextField(15);
        nameLabel = new javax.swing.JLabel();
        signupLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        newUserLabel.setBackground(new java.awt.Color(51, 51, 51));
        newUserLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        newUserLabel.setForeground(new java.awt.Color(57, 192, 186));
        newUserLabel.setText("New Username:");
        jPanel1.add(newUserLabel);
        newUserLabel.setBounds(420, 290, 200, 30);

        newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserActionPerformed(evt);
            }
        });
        jPanel1.add(newUser);
        newUser.setBounds(630, 290, 110, 30);

        newPassLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        newPassLabel.setForeground(new java.awt.Color(57, 192, 186));
        newPassLabel.setText("New Password:");
        jPanel1.add(newPassLabel);
        newPassLabel.setBounds(430, 380, 180, 20);

        repeatPassLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        repeatPassLabel.setForeground(new java.awt.Color(57, 192, 186));
        repeatPassLabel.setText("Repeat Password:");
        jPanel1.add(repeatPassLabel);
        repeatPassLabel.setBounds(410, 470, 210, 30);

        submit.setBackground(new java.awt.Color(45, 48, 55));
        submit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(57, 192, 186));
        submit.setText("SUBMIT");
        submit.setAutoscrolls(true);
        submit.setPreferredSize(new java.awt.Dimension(250, 125));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(630, 560, 110, 40);
        jPanel1.add(newPass);
        newPass.setBounds(630, 380, 110, 30);
        jPanel1.add(repeatPass);
        repeatPass.setBounds(630, 470, 110, 30);
        jPanel1.add(name);
        name.setBounds(630, 210, 110, 30);

        nameLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(57, 192, 186));
        nameLabel.setText("Name:");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(520, 210, 90, 30);

        signupLabel.setFont(new java.awt.Font("Century Gothic", 0, 52)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(57, 192, 188));
        signupLabel.setText("Sign Up...");
        jPanel1.add(signupLabel);
        signupLabel.setBounds(20, 10, 250, 60);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fill in the information:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 100, 520, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/registerBG.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1366, 735);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(checkUsername() && checkPassword()){
            try {
                jdbc.execute("user","(\""+newUser.getText()+"\",\""+newPass.getText()+"\",\""+name.getText()+"\")","(username,password,name)");
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                b = new Mainmenu();
                /*try {
                JDBC test = new JDBC();
                test.execute("user", "(\""+newUser.getText()+"\","+ repeatPass.getText()+"\")", "(username, password)"); //ใส่ user
                } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.dispose();
            b.setVisible(true);
        }
 
    }//GEN-LAST:event_submitActionPerformed

    private void newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newUserActionPerformed

    private boolean checkUsername(){
        //Check that Username is contains only letters or numbers
        Pattern p = Pattern.compile("^[A-z0-9]*$");
        Matcher m = p.matcher(newUser.getText());
        boolean b = m.matches();
        if(newUser.getText().compareTo("") == 0 || newUser.getText().length() > 10 || b == false){
            newUser.setText("");
            newUser.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Username Error");
            return false;
        }
        newUser.setBackground(Color.green);
        return true;
    }
    
    private boolean checkPassword(){
        //Check that password is contains only letters or numbers
        Pattern p = Pattern.compile("^[A-z0-9]*$");
        Matcher m = p.matcher(newPass.getText());
        boolean b = m.matches();
        if(newPass.getText().compareTo(repeatPass.getText()) != 0 || newPass.getText().isEmpty() || repeatPass.getText().isEmpty()){
            repeatPass.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Password Error");
            return false;
        }
        else if(newPass.getText().length() > 10 || b == false){
            newPass.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Password Error");
            return false;
        }
        newPass.setBackground(Color.green);
        repeatPass.setBackground(Color.green);
        return true;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Register().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JTextField newUser;
    private javax.swing.JLabel newUserLabel;
    private javax.swing.JPasswordField repeatPass;
    private javax.swing.JLabel repeatPassLabel;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
